name: Setup Bun

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Format"]
    types:
      - completed

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.2

      - name: Install dependencies
        run: bun install

      - name: Set environment variables
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> $GITHUB_ENV

      - name: Run build
        run: bun run build
